const tickets = [
  {
    category: "Q1 2022",
    color: "red",
    title: "NFT Safety 101 Video",
    owner: "Ania Kubow",
    avatar: " https://randomuser.me/api/portraits/women/72.jpg",
    status: "done",
    priority: 5,
    progress: 40,
    description: "Make sth ",
    timestamp: "2022-02-11T07:36:17+0000",
  },
  {
    category: "Q1 2022",
    color: "violet",
    title: "Fix 101 Video",
    owner: "Ania Kubow",
    avatar: "https://randomuser.me/api/portraits/women/87.jpg",
    status: "working on it",
    priority: 2,
    progress: 70,
    description: "Make sth good ",
    timestamp: "2022-02-11T07:36:17+0000",
  },
  {
    category: "Q2 2022",
    color: "blue",
    title: "Buid 101 Video",
    owner: "Ania Kubow",
    avatar: "https://randomuser.me/api/portraits/women/83.jpg",
    status: "working on it",
    priority: 3,
    progress: 10,
    description: "Make sth video",
    timestamp: "2022-02-11T07:36:17+0000",
  },
];
